{% set name = "pyRestTable" %}
{% set version = "2020.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b6fd6ead9f1a9601eb152156e615827cff3340f46830ef07ef2d8781147b5b78

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - python >=3.7
    - lxml

test:
  imports:
    - pyRestTable

about:
  home: https://github.com/prjemian/pyRestTable
  license: CC-BY-4.0
  license_file: {{ name }}/LICENSE.txt
  summary: Format a nice table in reST (reStructuredText) from Python

extra:
  recipe-maintainers:
    - mrakitin
    - prjemian
    - kbeeperez
