{% set name = "pyRestTable" %}
{% set version = "2020.0.7rc1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4962c57643176bf3b3a0b086b2764f0a03f97e7a74705b49c30ab78735b94a39

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - python >=3.7
    - lxml

test:
  imports:
    - pyRestTable

about:
  home: https://github.com/prjemian/pyRestTable
  license: CC-BY-4.0
  license_file: {{ name }}/LICENSE.txt
  summary: Format a nice table in reST (reStructuredText) from Python

extra:
  recipe-maintainers:
    - mrakitin
    - prjemian
    - kbeeperez
