{% set name = "pyRestTable" %}
{% set version = "2020.0.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: 56932228cdde1fe3b7b915985c19d2330968d6cf00b8002f9347e0718442cac5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools-scm
  run:
    - python >={{ python_min }}
    - lxml

test:
  requires:
    - python {{ python_min }}
  imports:
    - pyRestTable

about:
  home: https://github.com/prjemian/pyRestTable
  license: CC-BY-4.0
  license_file: {{ name }}/LICENSE.txt
  summary: Format a nice table in reST (reStructuredText) from Python

extra:
  recipe-maintainers:
    - prjemian
    - mrakitin
    - kbeeperez
