{% set name = "pyRestTable" %}
{% set version = "2020.0.10" %}
{% set sha256 = "9b23db835e46b389c61a850e61aea1a7a5600b39c4707714e4fb655c1fbe7747" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools-scm
  run:
    - python >=3.9
    - lxml

test:
  imports:
    - pyRestTable

about:
  home: https://github.com/prjemian/pyRestTable
  license: CC-BY-4.0
  license_file: {{ name }}/LICENSE.txt
  summary: Format a nice table in reST (reStructuredText) from Python

extra:
  recipe-maintainers:
    - prjemian
    - mrakitin
    - kbeeperez
