{% set name = "pyRestTable" %}
{% set version = "2020.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c262e7f31fd0f50f58ceaacefe380d423b2c0b62e5e3268186c393ac44ff6d41

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - python >=3.7
    - lxml

test:
  imports:
    - pyRestTable

about:
  home: https://github.com/prjemian/pyRestTable
  license: CC-BY-4.0
  license_file: {{ name }}/LICENSE.txt
  summary: Format a nice table in reST (reStructuredText) from Python

extra:
  recipe-maintainers:
    - mrakitin
    - prjemian
    - kbeeperez
